AllCops:
  TargetRubyVersion: 3.4
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

inherit_gem: { rubocop-37signals: rubocop-ruby.yml }
